### ISSUE TITLE
Issue with embed.py

### ISSUE THREAD

**Issue by sshsurabhi** [VisualComputingInstitute/triplet-reid#42] opened 2018-06-19 23:46 UTC
ssur@suresure:~$ python3 /home/ssur/triplet-reid-master/embed.py --experiment_root /home/ssur/experiments/my_experiment --dataset /home/ssur/triplet-reid-master/data/market1501_query.csv     --filename test_embeddings.h5
Loading args from /home/ssur/experiments/my_experiment/args.json.
Evaluating using the following parameters:
aggregator: None
batch_k: 4
batch_p: 32
batch_size: 256
checkpoint: None
checkpoint_frequency: 1000
crop_augment: None
dataset: /home/ssur/triplet-reid-master/data/market1501_query.csv
decay_start_iteration: 15000
detailed_logs: False
embedding_dim: 128
experiment_root: /home/ssur/experiments/my_experiment
filename: /home/ssur/experiments/my_experiment/test_embeddings.h5
flip_augment: False
head_name: fc1024
image_root: /home/ssur/Market-1501-v15.09.15
initial_checkpoint: None
learning_rate: 0.0003
loading_threads: 8
loss: batch_hard
margin: soft
metric: euclidean
model_name: resnet_v1_50
net_input_height: 256
net_input_width: 128
pre_crop_height: 288
pre_crop_width: 144
quiet: False
resume: False
train_iterations: 25000
train_set: /home/ssur/triplet-reid-master/data/market1501_train.csv
Traceback (most recent call last):
  File "/home/ssur/triplet-reid-master/embed.py", line 249, in <module>
    main()
  File "/home/ssur/triplet-reid-master/embed.py", line 160, in main
    num_parallel_calls=args.loading_threads)
  File "/home/ssur/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 853, in map
    return ParallelMapDataset(self, map_func, num_parallel_calls)
  File "/home/ssur/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1870, in __init__
    super(ParallelMapDataset, self).__init__(input_dataset, map_func)
  File "/home/ssur/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1839, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/home/ssur/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 484, in add_to_graph
    self._create_definition_if_needed()
  File "/home/ssur/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 319, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/ssur/.local/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 336, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/home/ssur/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1827, in tf_map_func
    ret, [t.get_shape() for t in nest.flatten(ret)])
  File "/home/ssur/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1827, in <listcomp>
    ret, [t.get_shape() for t in nest.flatten(ret)])
AttributeError: 'str' object has no attribute 'get_shape'

I am trying to re-implement the code. for the training, it went well. but when I am trying to test... I am getting a problem with this code embed.py    ............. please help me out.        

Thank you

**Comment by lucasb-eyer** [comment] 2018-06-20 05:45
Hi, thanks for the report. This is a duplicate of #40 (though not obvious from that issue's title) and we solved it already. Are you using the lastest master? Do `git pull` in your folder to get it.

I'm already closing this issue because I'm pretty sure, but please re-open it if you still have the error in the latest version of our code.

**Closed by lucasb-eyer** 2018-06-20 05:45 UTC
