### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by jerry-chenrb** [VisualComputingInstitute/triplet-reid#82] opened 2019-07-24 12:32 UTC
when i run my image dadaset,alwayes wrong,can not find the image ,like that:No such file or directory，but i don not think the reason  is image path,because,if i run it again,the number of wrong image will be changed.
![image](https://user-images.githubusercontent.com/53084996/61793438-ba23c080-ae51-11e9-9a5a-f51bf2f6d3d1.png)
![image](https://user-images.githubusercontent.com/53084996/61793667-34544500-ae52-11e9-91f8-93354b6a2fb6.png)

**Comment by Pandoro** [comment] 2019-07-30 12:30
If by "if i run it again,the number of wrong image will be changed." you mean that the actual image that is not found changes, that is probably due to the way we sample batches from a list of images and only load them afterwards.

To me a path starting with `train_image/home/ubuntu/...` does not make sense. Probably something went wrong with the way you used the `image_root` argument. The image root is prepended to the files descriptions in the dataset csv files and that is used as the final image path. Maybe you use `--image_root train_image` while giving full file specifications in your csv files?

This is not a bug on our side though. Make sure your image paths are valid. Feel free to comment if that still does not work. I'm closing this though.

**Closed as completed by Pandoro** 2019-07-30 12:30 UTC
Labels: question (not issue)

**Comment by jerry-chenrb** [comment] 2019-07-31 01:23
Thank you very much for your reply. I have solved this problem only because of the inconsistency of image size in my data set. Now I am training. I find loss is very low. I think I should stop training, because the training after that is not very effective. So I went to the evaluation section, but I didn't understand what you said about the.. embeddings. H5 file. How did it generate? Is it automatically generated in experience after training, or do you make. H5 files by yourself? I hope you can explain it in detail.

**Comment by jerry-chenrb** [comment] 2019-07-31 01:24
Thank you very much for your reply. I have solved this problem only because of the inconsistency of image size in my data set. Now I am training. I find loss is very low. I think I should stop training, because the training after that is not very effective. So I went to the evaluation section, but I didn't understand what you said about the.. embeddings. H5 file. How did it generate? Is it automatically generated in experience after training, or do you make. H5 files by yourself? I hope you can explain it in detail

**Comment by jerry-chenrb** [comment] 2019-07-31 07:55
Thank you very much for your answer. Now I have new doubts. I can't start. I hope you can give me a reply as soon as possible




------------------ 原始邮件 ------------------
发件人: "Alexander Hermans"<notifications@github.com>;
发送时间: 2019年7月30日(星期二) 晚上8:31
收件人: "VisualComputingInstitute/triplet-reid"<triplet-reid@noreply.github.com>;
抄送: "1317054806"<1317054806@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [VisualComputingInstitute/triplet-reid] Images not found (#82)




If by "if i run it again,the number of wrong image will be changed." you mean that the actual image that is not found changes, that is probably due to the way we sample batches from a list of images and only load them afterwards.
 
To me a path starting with train_image/home/ubuntu/... does not make sense. Probably something went wrong with the way you used the image_root argument. The image root is prepended to the files descriptions in the dataset csv files and that is used as the final image path. Maybe you use --image_root train_image while giving full file specifications in your csv files?
 
This is not a bug on our side though. Make sure your image paths are valid. Feel free to comment if that still does not work. I'm closing this though.

**Comment by Pandoro** [comment] 2019-07-31 12:55
How to generate the embeddings is discussed in the Readme. I cannot explain it more clearly than already done there.
